sudo: true
language: csharp
solution: GameServer.sln
dist: trusty
mono: none
install:
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    - echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list
    - sudo apt-get update
    - sudo apt-get -y install mono-devel
    - sudo apt-get install nuget
    - wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - sudo mono nuget.exe restore GameServer.sln
script:
    - xbuild /p:Configuration=Debug GameServer.sln
notifications:
    email: false
